export { default as image1 } from "../../public/img/01.jpg";
export { default as image2 } from "../../public/img/02.jpg";
export { default as image3 } from "../../public/img/03.jpg";
export { default as image4 } from "../../public/img/04.jpg";
export { default as image5 } from "../../public/img/05.jpg";
export { default as image6 } from "../../public/img/06.jpg";
export { default as arrow } from "../../public/icons/arrow.svg";
export { default as reactlogo } from "../../public/icons/React-icon.svg";
export { default as avatar } from "../../public/img/avatar.jpg";